### ISSUE TITLE
Service autoscaling

### ISSUE THREAD

**Issue by rmichela** [salesforce/helm-starter-istio#29]
```
autoscaling:
  minReplicas: 3
  maxReplicas: 6
  targetAverageUtilization: 80
```
